spring:
  application:
    name: missaojavacomgradle
  profiles:
    active: ${SERVER_ENV}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20000
  data:
    mongodb:
      authentication-database: admin
      database: SBanco
      uri: ${MONGODB_URI}
  datasource:
    url: jdbc:h2:~/data/SBanco;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;SCHEMA=public
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    jpa:
      defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: ${FLY_WAY_DB_ENABLE:true}
    url: jdbc:h2:~/data/SBanco;DB_CLOSE_DELAY=-1
    user: sa
    password: password
    clean-disabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    encoding: UTF-8
    outOfOrder: false
    schemas: public
    validate-on-migrate: true

  kafka:
    producer:
      buffer-memory: 31457280
      message-max-bytes: 31457280
      max-request-size: 31457280
      bootstrap-servers: broker1:9192
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        max:
          request:
            size: 31457280
    consumer:
      bootstrap-servers: broker1:9192
      group-id: group-id-crud-usuario
      auto-offset-reset: earliest
      message-max-bytes: 31457280
      max-partition-fetch-bytes: 31457280
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080

h2-server:
  port: 8081

logging:
  level:
    web: ${LOG_LEVEL:debug}
    org.mongodb: ${MONGODB_LOG_LEVEL:debug}
    co.sban: ${LOG_LEVEL:debug}
    org.springframework.web: ${SPRING_LOG_LEVEL:debug}
    org.springframework.boot.autoconfigure.mongo.embedded: ${MONGODB_LOG_LEVEL:debug}

crud:
  kafka:
    listen:
      auto:
        start: ${KAFKA_LISTEN_AUTO_START:true}